import * as React from "react";
import {
  CalendarClock,
  DoorOpen,
  Camera,
  Sparkles,
  Shirt,
  Scale,
  Bed,
  Clock,
} from "lucide-react";
import type { StepData } from "@/components/home/how-it-works-step";

export type ServiceKey = "bag" | "kg" | "bedding" | "express";

export interface ServiceConfig {
  id: ServiceKey;
  label: string;
  badge: string;
  price: string;
  icon: React.ElementType;
  steps: StepData[];
}

export const SERVICES_DATA: Record<ServiceKey, ServiceConfig> = {
  bag: {
    id: "bag",
    label: "Bag Wash & Fold",
    badge: "2+ Bags = FREE Delivery",
    price: "$32.50 / bag (about 2 loads)",
    icon: Shirt,
    steps: [
      {
        id: 1,
        numberStr: "01",
        shortLabel: "1. Pick Your Time",
        badge: "8am–12pm & 1pm–6pm",
        icon: CalendarClock,
        actionText: "Schedule 13-gallon bag pickup",
        detail: "Choose today, tomorrow, or a future slot in seconds.",
        helperNote: "No waiting around all day.",
      },
      {
        id: 2,
        numberStr: "02",
        shortLabel: "2. Doorstep Hand-off",
        badge: "Contactless Ready",
        icon: DoorOpen,
        actionText: "Leave bag outside or hand to driver",
        detail: "Specify Home or Away. If away, leave bag outside door.",
        helperNote: "Presence verification guaranteed.",
      },
      {
        id: 3,
        numberStr: "03",
        shortLabel: "3. Photo Verified",
        badge: "100% Transparent",
        icon: Camera,
        actionText: "Pickup photo proof logged",
        detail: "Driver logs weight, scans barcode, and snaps photo.",
        helperNote: "Zero lost or mixed bags.",
      },
      {
        id: 4,
        numberStr: "04",
        shortLabel: "4. Delivered Fresh",
        badge: "24h Turnaround",
        icon: Sparkles,
        actionText: "Washed, folded crisp & returned",
        detail: "Washed with selected detergent and folded crisp.",
        helperNote: "2+ Bags = FREE delivery!",
      },
    ],
  },
  kg: {
    id: "kg",
    label: "By-the-KG",
    badge: "$2.75 / KG",
    price: "$2.75 / kg",
    icon: Scale,
    steps: [
      {
        id: 1,
        numberStr: "01",
        shortLabel: "1. Pick Your Time",
        badge: "Morning or Afternoon",
        icon: CalendarClock,
        actionText: "Select bulk pickup slot",
        detail: "Pick convenient morning (8am–12pm) or afternoon window.",
        helperNote: "5 KG minimum per load.",
      },
      {
        id: 2,
        numberStr: "02",
        shortLabel: "2. Doorstep Hand-off",
        badge: "Hamper Ready",
        icon: DoorOpen,
        actionText: "Driver collects weighed laundry",
        detail: "Hand over hampers or request contactless porch pickup.",
        helperNote: "Commercial & Airbnb friendly.",
      },
      {
        id: 3,
        numberStr: "03",
        shortLabel: "3. Photo Verified",
        badge: "Digital Scale Proof",
        icon: Camera,
        actionText: "Precision digital scale photo logged",
        detail: "Accurate weight verified upon facility intake.",
        helperNote: "Pay exact verified weight.",
      },
      {
        id: 4,
        numberStr: "04",
        shortLabel: "4. Delivered Fresh",
        badge: "24h Turnaround",
        icon: Sparkles,
        actionText: "Sanitized, sorted & delivered",
        detail: "Deep washed, dried, sorted, and packed crisply.",
        helperNote: "Free delivery over $40!",
      },
    ],
  },
  bedding: {
    id: "bedding",
    label: "Bedding & Delicates",
    badge: "Hypoallergenic",
    price: "From $18.00",
    icon: Bed,
    steps: [
      {
        id: 1,
        numberStr: "01",
        shortLabel: "1. Pick Your Time",
        badge: "Flexible Windows",
        icon: CalendarClock,
        actionText: "Schedule comforter & linen care",
        detail: "Choose pickup slot for bulky duvets, blankets, or silks.",
        helperNote: "Fabric preservation care.",
      },
      {
        id: 2,
        numberStr: "02",
        shortLabel: "2. Doorstep Hand-off",
        badge: "Linens Bag",
        icon: DoorOpen,
        actionText: "Leave bedding in laundry hamper",
        detail: "Place outside door or hand to courier at scheduled time.",
        helperNote: "Sanitary individual handling.",
      },
      {
        id: 3,
        numberStr: "03",
        shortLabel: "3. Photo Verified",
        badge: "Fabric Inspection",
        icon: Camera,
        actionText: "Fabric inspection photo check",
        detail: "Garments inspected with pre-wash photo logging.",
        helperNote: "Guaranteed fabric safety.",
      },
      {
        id: 4,
        numberStr: "04",
        shortLabel: "4. Delivered Fresh",
        badge: "Hypoallergenic Clean",
        icon: Sparkles,
        actionText: "Ozone sanitized & fluffed",
        detail: "Low-heat dried, folded hotel-style, and sealed clean.",
        helperNote: "Ready for the bedroom!",
      },
    ],
  },
  express: {
    id: "express",
    label: "24h Express",
    badge: "Guaranteed 24h",
    price: "Fast Delivery",
    icon: Clock,
    steps: [
      {
        id: 1,
        numberStr: "01",
        shortLabel: "1. Pick Your Time",
        badge: "Priority Dispatch",
        icon: CalendarClock,
        actionText: "Book priority pickup window",
        detail: "Select earliest available pickup slot for urgent wash.",
        helperNote: "Dispatched immediately.",
      },
      {
        id: 2,
        numberStr: "02",
        shortLabel: "2. Doorstep Hand-off",
        badge: "Fast Track Route",
        icon: DoorOpen,
        actionText: "Fast courier porch intake",
        detail: "Driver alerted on priority route with live ETA updates.",
        helperNote: "Fastest doorstep pickup.",
      },
      {
        id: 3,
        numberStr: "03",
        shortLabel: "3. Photo Verified",
        badge: "Instant Timestamp",
        icon: Camera,
        actionText: "Instant pickup photo receipt",
        detail: "Photo uploaded immediately to confirm intake timestamp.",
        helperNote: "Real-time tracking active.",
      },
      {
        id: 4,
        numberStr: "04",
        shortLabel: "4. Delivered Fresh",
        badge: "Hero Turnaround",
        icon: Sparkles,
        actionText: "Guaranteed back in 24 hours",
        detail: "Fresh, clean, and folded at your door before deadline.",
        helperNote: "Hero turnaround guaranteed.",
      },
    ],
  },
};
