import type { Order, OrderReview } from "@/types";
import type { CustomerAccount } from "@/components/admin/customer-detail-modal";

/**
 * Laundry Express — Internal Administrative Mock Data Feed
 * Provides consistent data models for:
 * - Orders pipeline (active, picked up, in-wash, delivered)
 * - Customer directory (profiles, lifetime stats, past orders, Stripe payments)
 * - Customer review moderation
 */

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1",
    order_number: "LX-2026-0042",
    user_id: "u-1",
    pricing_mode: "per_bag",
    detergent_id: "det-tide-pods",
    bag_count: 2,
    pickup_date: "Today",
    pickup_slot: "8am-12pm",
    subtotal: 30.0,
    discount_amount: 0.0,
    delivery_fee: 0.0, // Free because >= 2 bags
    tax_amount: 0.0,
    total_amount: 30.0,
    is_out_of_home: true,
    bag_outside_door_confirmed: true,
    customer_notes: "Leave clean bags on front porch behind white chair.",
    has_preexisting_damage: true,
    damage_notes: "Frayed stitching on grey duvet cover (documented before wash).",
    damage_photo_url: "/brand/hero-mascot.png",
    customer_notified_damage: true,
    order_status: "in_wash",
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: "u-1",
      email: "sarah.jenkins@example.com",
      phone: "+1 (815) 575-9536",
      address: "1420 Algonquin Rd, Lake in the Hills, IL 60156",
      full_name: "Sarah Jenkins",
      role: "customer",
      is_active: true,
      created_at: "",
      updated_at: "",
    },
    proofs: [
      { id: "prf-1", order_id: "ord-1", proof_type: "pickup", image_url: "/brand/logo-badge.jpg", uploaded_by: "driver-1", created_at: new Date(Date.now() - 7200000).toISOString() },
      { id: "prf-2", order_id: "ord-1", proof_type: "damage", image_url: "/brand/hero-mascot.png", notes: "Frayed stitching", uploaded_by: "wash-lead", created_at: new Date(Date.now() - 3600000).toISOString() },
    ],
  },
  {
    id: "ord-2",
    order_number: "LX-2026-0043",
    user_id: "u-2",
    pricing_mode: "per_bag",
    detergent_id: "det-eco-plant",
    bag_count: 1,
    pickup_date: "Today",
    pickup_slot: "1pm-6pm",
    subtotal: 32.50,
    discount_amount: 0.0,
    delivery_fee: 10.0,
    tax_amount: 0.0,
    total_amount: 42.50,
    is_out_of_home: false,
    bag_outside_door_confirmed: false,
    customer_notes: "Ring doorbell twice upon arrival.",
    order_status: "confirmed",
    created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: "u-2",
      email: "marcus.rodriguez@example.com",
      phone: "+1 (815) 345-8912",
      address: "882 Pyott Rd, Lake in the Hills, IL 60156",
      full_name: "Marcus Rodriguez",
      role: "customer",
      is_active: true,
      created_at: "",
      updated_at: "",
    },
  },
  {
    id: "ord-3",
    order_number: "LX-2026-0044",
    user_id: "u-3",
    pricing_mode: "per_kg",
    detergent_id: "det-fragrance-free",
    bag_count: 0,
    estimated_weight_kg: 12.0,
    final_weight_kg: null,
    pickup_date: "Tomorrow",
    pickup_slot: "8am-12pm",
    subtotal: 33.0,
    discount_amount: 0.0,
    delivery_fee: 10.0,
    tax_amount: 0.0,
    total_amount: 43.0,
    is_out_of_home: true,
    bag_outside_door_confirmed: true,
    customer_notes: "Bulk Airbnb linens and bedsheets.",
    order_status: "driver_assigned",
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    user: {
      id: "u-3",
      email: "elena.rostova@example.com",
      phone: "+1 (815) 621-4402",
      address: "410 Randall Rd, Crystal Lake, IL 60014",
      full_name: "Elena Rostova",
      role: "customer",
      is_active: true,
      created_at: "",
      updated_at: "",
    },
  },
];

export const INITIAL_REVIEWS: OrderReview[] = [
  {
    id: "rev-pending-1",
    order_id: "ord-104",
    user_id: "u-4",
    rating: 5,
    comment: "The driver was here right at 8:15 AM! Folded clothes smelled so crisp and fresh. 10/10 recommend.",
    status: "pending",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    user: { full_name: "David Miller" },
    photos: [{ id: "p1", review_id: "rev-pending-1", photo_url: "/brand/logo-badge.jpg", display_order: 1, created_at: new Date().toISOString() }],
  },
];

export const INITIAL_CUSTOMERS: CustomerAccount[] = [
  {
    id: "cust-1",
    full_name: "Sarah Jenkins",
    email: "sarah.jenkins@example.com",
    phone: "+1 (815) 575-9536",
    address: "1420 Algonquin Rd, Lake in the Hills, IL 60156",
    joined_date: "Feb 14, 2026",
    orders: [
      INITIAL_ORDERS[0],
      {
        id: "ord-past-1",
        order_number: "LX-2026-0019",
        user_id: "u-1",
        pricing_mode: "per_bag",
        detergent_id: "det-tide-pods",
        bag_count: 2,
        pickup_date: "Sep 18, 2026",
        pickup_slot: "8am-12pm",
        subtotal: 30.0,
        discount_amount: 0.0,
        delivery_fee: 0.0,
        tax_amount: 0.0,
        total_amount: 30.0,
        is_out_of_home: false,
        bag_outside_door_confirmed: false,
        order_status: "completed",
        created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
        updated_at: new Date(Date.now() - 86400000 * 7).toISOString(),
      },
    ],
    reviews: [
      {
        id: "rev-s1",
        order_id: "ord-past-1",
        user_id: "u-1",
        rating: 5,
        comment: "Flawless doorstep service. Everything smelled clean and fresh!",
        status: "approved",
        created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    payments: [
      { id: "pi_38194a", amount: 30.0, date: "Sep 25, 2026", method: "Visa •••• 4242", status: "succeeded", order_number: "LX-2026-0042" },
      { id: "pi_11029b", amount: 30.0, date: "Sep 18, 2026", method: "Apple Pay", status: "succeeded", order_number: "LX-2026-0019" },
    ],
  },
  {
    id: "cust-2",
    full_name: "Marcus Rodriguez",
    email: "marcus.rodriguez@example.com",
    phone: "+1 (815) 345-8912",
    address: "882 Pyott Rd, Lake in the Hills, IL 60156",
    joined_date: "Mar 02, 2026",
    orders: [INITIAL_ORDERS[1]],
    reviews: [],
    payments: [
      { id: "pi_99214c", amount: 25.0, date: "Sep 26, 2026", method: "Mastercard •••• 8812", status: "succeeded", order_number: "LX-2026-0043" },
    ],
  },
  {
    id: "cust-3",
    full_name: "Elena Rostova",
    email: "elena.rostova@example.com",
    phone: "+1 (815) 621-4402",
    address: "410 Randall Rd, Crystal Lake, IL 60014",
    joined_date: "Jan 28, 2026",
    orders: [INITIAL_ORDERS[2]],
    reviews: [],
    payments: [
      { id: "pi_64210d", amount: 43.0, date: "Sep 26, 2026", method: "Google Pay", status: "succeeded", order_number: "LX-2026-0044" },
    ],
  },
  {
    id: "cust-4",
    full_name: "David Miller",
    email: "david.miller@example.com",
    phone: "+1 (815) 902-1144",
    address: "215 Virginia St, Crystal Lake, IL 60014",
    joined_date: "Feb 10, 2026",
    orders: [],
    reviews: [INITIAL_REVIEWS[0]],
    payments: [
      { id: "pi_77192e", amount: 35.0, date: "Sep 20, 2026", method: "Visa •••• 1044", status: "succeeded", order_number: "ord-104" },
    ],
  },
];
